### ISSUE TITLE
Nexus 6P sensor issues

### ISSUE THREAD

**Issue by gappleto97** [sky-map-team/stardroid#118]
Problem: the map will momentarily flicker from one place to another (span: 1 frame). It also responds very poorly to movement along the East/West axis, to the point of simply refusing to point in that direction. 

So I tried the following:

* all combinations of damping/sensor speed (some alleviated the east/West problem a little, but the jitter remained constant) 
* investing z axis (no effect at all) 
* disabling magnetic correction (no improvement) 

Going into the diagnostic info, there seems to be a lot of noise, and the compass information swings by ~20 degrees when I rotate 90 degrees. Not sure if this is a unit conversion, but this seemed odd. 

Then I read in a product forum that this is a common problem with apps not expecting this level of detail, so I thought it might be good to bring it up. Normally I wouldn't bring up a sensor noise complaint, but this seems to be a software, rather than hardware problem. Especially as I know Google's photo sphere and Open Camera's photo sphere seem to both work.

**Comment by jaydeetay** [comment]
Hi Gabe,
Thanks for your bug report.  The main difference between the apps you
mention and Sky Map is both of those other apps will use your 6P's
gyroscope while Sky Map does not.  This gives much smoother movement data
than the compass which is *really* noisy (as you've discovered for
yourself).  The smoothing code for the compass is not buggy (as far as I
know) but it is old, the method not particularly great and tuned for the
phones that existed 7 years ago.

The right solution here is for us to start using the gyroscope.  We have an
alpha version of the app that does just that.  Want to try it?

John

**Comment by gappleto97** [comment]
Sure. Can you point me towards a download?

**Comment by jaydeetay** [comment]
Sure Gabe.  Can you sign up here:
https://play.google.com/apps/testing/com.google.android.stardroid
and send us (skymapdevs@gmail.com) your email address so we can whitelist you.

**Comment by gappleto97** [comment]
Got the alpha. Much less jitters, but the East/West problem is even worse now. I can't get it to point in any direction but south-southwest.

**Comment by jaydeetay** [comment]
Thanks for the report Gabe.  Here's a thought - do you have the phone in a case with a cover?

**Comment by gappleto97** [comment]
I do not. And I specifically made sure to test it without the cover last time. 

Oddly enough, the app worked perfectly fine later in the day. It was off by <10 degrees the entire time, with no jitters. I wonder if when I first tested I was getting interference from the buildings? 

The only complaint I have about the alpha now is that the names no longer match orientation. If the problem comes back I'll let you know. Next time I'll be out looking is Friday, so I won't mind if you close this until then.

**Comment by jaydeetay** [comment]
Hi Gabe,
Just checking in to see if the latest version of Sky Map solved your problem.  I think with your East/West problem it was probably just a compass miscalibration that corrected itself (the device needs to be waved around a fair bit before the compass calibrates itself).

**Comment by jaydeetay** [comment]
Please reopen if it's still an issue for you.
