### ISSUE TITLE
Add Epsilon Lyrae to tracked objects

### ISSUE THREAD

**Issue by gappleto97** [sky-map-team/stardroid#119]
I'd like to find the Double Double a bit more easily :)

**Comment by jaydeetay** [comment]
Sure we can add this one.  In general I want to give our data a thorough
overhaul, but I'm happy to make the occasional one off change.

**Comment by KevinSerafini** [comment]
We currently track named stars, planets, and Messier objects. We don't
track other things. I think its easy enough to track Epsilon Lyrae as a
star, though.

The current assumption is that the user is not using additional optics (Mk
1 eyeball, only). I've been tempted to make a separate version of the app
more geared toward amateur astronomers vs the general public. A couple of
additions come to mind... stars to mag 7-8 (i.e., what you can see in
binoculars), moons of jupiter (possibly in a separate view), rings of
saturn (again, in a separate view), bright double stars, interesting NGC
objects (maybe to mag 8 or so), eclipse finder, and more information for
the objects (rise/set, mag, RA/DEC, etc.).

I still think the bulk of our users are casual folks just trying to figure
out what that bright star is. Or to find the Big Dipper. :)

On Thu, Jun 2, 2016 at 11:45 PM, John David Taylor <notifications@github.com

**Comment by jaydeetay** [comment]
I was out in the wilds this weekend and what we currently show is about on
the limit of what my old eyes can see.

Kevin - do you want to take this one or shall I bundle it into a bunch of
other bug fixes I'm doing for the next release?
