### ISSUE TITLE
Time does not update (quickly) after app is backgrounded.

### ISSUE THREAD

**Issue by jaydeetay** [sky-map-team/stardroid#120]
To repro: start the app, send it to the background, bring it to the foreground some time later, the stars will be out of position.

**Comment by KevinSerafini** [comment]
This is an old bug, right? I seem to remember this being an issue back in
the day.

On Thu, Jun 2, 2016 at 11:47 PM, John David Taylor <notifications@github.com

**Comment by jaydeetay** [comment]
Could be a dupe - I just noticed it when testing the gyro stuff.
