### ISSUE TITLE
Remove analytics for F-Droid

### ISSUE THREAD

**Issue by jspricke** [sky-map-team/stardroid#128]
Hi,

would it be possible to remove analytics, make it optional, or replace it by something free like [ACRA](https://github.com/ACRA/acra)? Currently Sky Map can't be build in F-Droid because of this, and it would be great to have it back:

https://f-droid.org/wiki/page/com.google.android.stardroid

**Comment by hurradiegams** [comment]
I second that.

**Comment by jaydeetay** [comment]
Hi - I actually don't know much about F-droid - I'm not sure how the app ended up on there in the first place...I don't think it was us (though I could be mistaken).  I understand people feel strongly about these things, but I want to keep the analytics - they're really useful.  Without them I wouldn't have found out that 10%+ of our users have phones that don't have compasses.  If it had been 0.1% I would have removed the app for such users - for 10% it seemed worth doing what we could for them.  So the analytics are going to stay.

But...if someone wants this badly why not fork the code and remove the analytics and put a build on F-droid?  The analytics code is all contained in one class and should be easily excised.  I'd prefer you didn't call it Sky Map, but the code is there for the taking.

**Comment by Paviluf** [comment]
I'd really like to have a version without analytics too. @jaydeetay should it be possible to add a build parameter, or something like that, to choose to enable or disable analytics ? I'm not against a fork but I think it's overkill for just not using analytics.

Thanks !

**Comment by jspricke** [comment]
I'm working on a patchset here: https://github.com/jspricke/stardroid/tree/fdroid. At the moment the names of the stars are wrong, but it works otherwise. Help welcome.

**Comment by barbeau** [comment]
For this to be sustainable it really needs to be implemented as a Gradle
build variant:
https://developer.android.com/studio/build/build-variants.html

**Comment by jspricke** [comment]
I used  build flavours:

https://github.com/jspricke/stardroid/commit/35aafb60cb5d4945a9b7561c9dc9135e9751fe45

would build variants be more appropriate?

**Comment by Paviluf** [comment]
> At the moment the names of the stars are wrong, but it works otherwise.

Can it be related ? https://github.com/sky-map-team/stardroid/issues/87

**Comment by jspricke** [comment]
No, they are completely wrong like "Settings" or "Place found" coming from here: https://github.com/sky-map-team/stardroid/blob/master/app/src/main/res/values/strings.xml. Interestingly it's working fine when I link play-services-location again (although I don't use it).

**Comment by barbeau** [comment]
@jspricke that works! Same thing.

**Comment by jaydeetay** [comment]
Ugh.  The way we do strings right now is pretty terrible (and accounts for our weird build process).  jspricke@  if you regenerate the data files does that fix it?

Instructions that may or may not be out of date here:  https://github.com/sky-map-team/stardroid/blob/master/tools/README.md

**Comment by jspricke** [comment]
Strings are fine for both build flavours now. I missed an error during the rebuild first but added a check to the build script now, see: https://github.com/sky-map-team/stardroid/pull/162/commits/8f00e17e447873fb70d717f1f7100180b6bd6459
