### ISSUE TITLE
Travis builds are failing

### ISSUE THREAD

**Issue by barbeau** [sky-map-team/stardroid#143]
Opening an issue to capture what we currently know.

Initial Travis configuration was merged via https://github.com/sky-map-team/stardroid/pull/137.

However, [builds are still failing](https://travis-ci.org/sky-map-team/stardroid/builds/145445267) with the message:

>Tests on test(AVD) - 6.0 failed: Instrumentation run failed due to 'Process crashed.'
com.android.builder.testing.ConnectedDevice > No tests found.[test(AVD) - 6.0] FAILED 
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @ Test annotations).
:app:connectedDebugAndroidTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:connectedDebugAndroidTest'.
> There were failing tests. See the report at: file:///home/travis/build/sky-map-team/stardroid/app/build/reports/androidTests/connected/index.html

Other potential wrinkle is that if any tests rely on Google APIs or Google Play Services, there is currently a problem getting a working Google API emulator running on Travis.  I'm not sure if this impacts stardroid?

If it does, relevant issues are:

* Android-maps-utils - https://github.com/googlemaps/android-maps-utils/issues/284
* Travis - https://github.com/travis-ci/travis-ci/issues/6122

I believe we're stuck waiting on Travis for resolution for this specific problem, see that issue for latest.

**Comment by barbeau** [comment]
I can't reproduce this error when running `gradlew app:connectedAndroidTest -PdisablePreDex` on a Windows machine with an x86 emulator with HAXM enabled.  I'm guessing it might have something to do with slower arm emulator execution, so I'm currently trying to repro locally on that configuration.

**Comment by jaydeetay** [comment]
I don't know what's going here either.  This build target executes fine for me on OSX.  Originally I thought the issue was a failing test (which I removed), but I think they're all green now.  Do you know a way to pull the test report mentioned in the stacktrace?

**Comment by barbeau** [comment]
I'm definitely not a Travis expert, but AFAIK Travis builds are ephemeral, so you'd have to push the log file to an external resource (e.g., FTP, Github) at the end of the build the same way you'd push a generated APK.  On a related note, I just found out in https://github.com/travis-ci/travis-ci/issues/6122#issuecomment-235792183 that there is a Travis Docker image (https://quay.io/repository/travisci/travis-android) that we could use to try to reproduce locally in the actual Travis environment.

**Comment by barbeau** [comment]
Related to the "Instrumentation run failed due to 'Process crashed.'" error - from https://github.com/robotiumtech/robotium/issues/249#issuecomment-132643174:

>Problem is not with testcase problem is with application. See if you use System.exit(0) anywhere in the application. It causes instrumentation test runner to run. Because it causes Dalvik virtual machine to exit. This result in finalization of all the objects. Use finish() instead of System.exit(0).

After searching the project, I saw `System.exit(1);` (which I assumed would have similar result) in the following classes:

* `AbstractProtoWriter`
* `AsciiProtoRewriter`
* `AsciiToBinaryProtoWriter`

However, I removed them in [this build](https://travis-ci.org/barbeau/stardroid/builds/147936211) and still got the same error message.

**Comment by barbeau** [comment]
I also haven't been able to reproduce this issue on an armeabi-v7a emulator locally on a Windows machine.

**Comment by barbeau** [comment]
The only other lead I have is related to the "com.android.builder.testing.ConnectedDevice > No tests found.[test(AVD) - 6.0] FAILED" message:
http://stackoverflow.com/questions/34042730/no-tests-found-for-instrumentation-tests-for-lollipop-and-above

Seems like it might be related to Dagger and/or certain annotations, and maybe this manifests on Travis in particular?  The tests are definitely configured differently than most other projects I've worked with, due to the project's origin with the older build systems pre-Gradle.

Per Jake Wharton's suggestion in https://github.com/google/dagger/issues/271#issuecomment-163977140 I tried configuring [gradle-apt-plugin](https://github.com/tbroyer/gradle-apt-plugin), and Travis is currently running [a build for that](https://travis-ci.org/barbeau/stardroid/builds/149073453).

**Comment by jaydeetay** [comment]
Thanks Sean.  I believe those Writer classes only get used for the
regeneration of the data files in assets/ , so they shouldn't be involved
in normal tests or app execution.

**Comment by barbeau** [comment]
No luck with the above build trying to address potential dagger issue.  I also tried running on a Kitkat emulator, but [that build failed as well](https://travis-ci.org/barbeau/stardroid/builds/150629120) with the same error.

**Comment by barbeau** [comment]
For future troubleshooting purposes, there are some good debugging script statements in [this commit](https://github.com/ardock/android-maps-utils/commit/a4fa636d21a6dfb7470bee16d0ddec14e7d312ea).

**Comment by marcomorain** [comment]
<3 @barbeau thanks for leaving that note!

![image](https://user-images.githubusercontent.com/448001/27088531-d1ddb42c-504f-11e7-9ca9-57c2dac9da08.png)
