### ISSUE TITLE
The send usage statistics option should be turn offable when on cellular

### ISSUE THREAD

**Issue by jidanni** [sky-map-team/stardroid#165]
Users would like to help out and send usage records however they would like to not do it when on cellular in order not to waste money, so give them the additional choice please.

**Comment by jaydeetay** [comment]
Unfortunately, as best I can tell, the Firebase Analytics library doesn't give the option to do this:

https://stackoverflow.com/questions/38265559/how-to-send-firebase-analytics-data-only-when-wi-fi-is-on
