### ISSUE TITLE
The latest version is not in PlayStore

### ISSUE THREAD

**Issue by Torvin** [sky-map-team/stardroid#173]
I can see **Version 1.9.2 (1480) May 20, 2017** in [F-Droid](https://f-droid.org/packages/com.google.android.stardroid/), but not in [PlayStore](https://play.google.com/store/apps/details?id=com.google.android.stardroid) (the latest version there is dated **September 27, 2016**).

Is that intentional? Should we expect the latest version published to PlayStore anytime soon?

**Comment by jaydeetay** [comment]
I think the date on the F-Droid version just reflects the fact that it's a recent build that removes the non-Free libraries.  In all other respects the versions should be the same.
