### ISSUE TITLE
Declination grid: odd calibration and missing annotations

### ISSUE THREAD

**Issue by ricknun** [sky-map-team/stardroid#176]
**Summary:** 

The declination grid uses 9 degrees per line and is not annotated.

**Steps to reproduce:** 

Turn off all display layers and then turn on Constellations, Right Ascension and Declination Grid, and Manual Mode.  Look at the Right Ascension and Declination grid lines.

**Expected behavior:** 

One declination ring every 10 degrees, and declination annotated from -80 to +80 degrees, every 20 degrees skipping 0, on the right ascension = 0h and 12h lines.

**Observed behavior:** 

Notice on the screenshot that there are 9 Declination rings between the horizon and North Pole, or 10 steps to cover 90 degrees.  1 ring represents 90/10 = 9 degrees.  None of the declination circles are annotated (similar to how Right Ascension is annotated from "0h" to "22h" every 2 hours along the celestial equator)
![screenshot_2017-10-09-12-46-32](https://user-images.githubusercontent.com/6921857/31355790-7dd57c22-acf0-11e7-94e1-3cd6775ad74b.png)
.

**Device and Android version:** 

Samsung Galaxy S5 phone running Android 6.0.1.

**Screenshots:** 

See the attached screenshot.

**Comment by jaydeetay** [comment]
Thanks for the bug report!
Fixed in: https://github.com/sky-map-team/stardroid/pull/343
