### ISSUE TITLE
Declination should have 9 divisions, not 10

### ISSUE THREAD

**Issue by adrianmay** [sky-map-team/stardroid#179]
**Summary:** 

Between the celestial equator and the pole, there are 90 degrees, therefore the should be 9 divisions, not 10.

**Steps to reproduce:** 

Open the app, find the pole and the equator, enable the grid, count the divisions.

**Expected behavior:** 

9 divisions, i.e. 
* a dot for the North pole, 
* 8 rings around it in the North
* the equator, 
* another 8 rings in the south,
* a dot for the south pole

**Observed behavior:** 

One ring too many in both North and South

**Device and Android version:** 

Irrelevant

**Screenshots:** 
 
None.

**Comment by jaydeetay** [comment]
Fixed in https://github.com/sky-map-team/stardroid/pull/343

**Comment by jaydeetay** [comment]
Thanks for the bug report!
