### ISSUE TITLE
Invitation to Mentor in GSoC 2018

### ISSUE THREAD

**Issue by heychirag** [sky-map-team/stardroid#180]
Hi

This has been one of my favourite apps for a long time. But it looks like the sheer lack of time has made this amazing open source project dead. Therefore I would like to take this opportunity to invite you guys to mentor this project under our organization [AOSSIE](https://aossie.gitlab.io/) as part of the 2018 edition of  [Google Summer of Code](https://summerofcode.withgoogle.com/).

Looking forward to an active response.

On a side note: If you are not willing to commit a major chunk of your time for this, you could then consider becoming a supervisor to a group of mentors from our organization. They'll be then looking after the major jobs like reviewing and testing code and taking pointers from you from time to time.

Warm Regards

**Comment by getsanjeev** [comment]
@heychirag I have checked out our gitter channel many times, there is always this mention of migrating the project to react-native. Also https://gitlab.com/aossie/stardroid is not there. Since this project does not seem active, How should I go about this? Are we not considering this project for summer of code'18?

**Comment by heychirag** [comment]
@jaydeetay Could you please address this?

**Comment by jaydeetay** [comment]
Hi folks,
Sorry I totally missed this.  This project isn't dead as such, but it's certainly slumbering. It gets love and attention in bursts as and when I can spare time from my day job.

So what's your plan here? You want to take the existing code and port it to a modern framework or language?
