### ISSUE TITLE
Link in readme to play store is broken

### ISSUE THREAD

**Issue by xenotropic** [sky-map-team/stardroid#192]
I think the title says it all, want to know easiest way to obtain fully open source build of this.

**Comment by QJKX** [comment]
https://f-droid.org/app/com.google.android.stardroid

**Comment by xenotropic** [comment]
Thanks. Bug should remain open, since the repository description (not the readme as I said in the title, sorry) has a dead link to the Google Play store in it. Seems like it should be replaced with this F-droid link.

**Comment by jaydeetay** [comment]
The link to the Play Store is working again now.  Play took the app down because we'd forgotten to tick a new checkbox in the app's description.  Thanks for flagging this.
