### ISSUE TITLE
FDroid version is broken.

### ISSUE THREAD

**Issue by jaydeetay** [sky-map-team/stardroid#205]
I believe that that Fdroid build of SkyMap is broken because the datafiles aren't correct for it.  They've been generated against the GMS version and somehow there's some skew in the resource ids for the fdroid version.  I suspect we can have the files compatible with one or the other.
The real solution here is to get rid of our byzantine build system.

**Comment by jspricke** [comment]
The F-Droid version works fine for me and others, what makes you believe it does not? Note that F-Droid regenerates the datafiles: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.google.android.stardroid.yml#L65
Cleaning up the build system sounds like a worthwhile goal anyhow :).

**Comment by jaydeetay** [comment]
Can't remember the exact circumstances when I wrote this bug (lesson: write better bugs).  IIRC it was something to do with our gradle configuration so I "temporarily" disabled that flavor with the intention of cleaning things up. That was two years ago of course. I'll still keep this bug around until I've re-enabled it.
