### ISSUE TITLE
Russian translation is wrong

### ISSUE THREAD

**Issue by hglade** [sky-map-team/stardroid#218]
**Summary:** 

'ecliptic' translated as 'эклептика' for ecliptic line. Should be 'эклиптика'.

**Steps to reproduce:** 

Main functionality map.

**Expected behavior:** 

Write 'эклиптика' instead of 'эклептика'.

**Observed behavior:** 

'ecliptic' translated as 'эклептика' for ecliptic line. Should be 'эклиптика'.

**Device and Android version:** 

Xiaomi Redmi Note 5 AI device. Android version 8.1.0, stock version ROM?  What version of Google Play Services version is 12.5.15.

**Screenshots:** 

--

**Comment by jaydeetay** [comment]
Thanks for this report!
