### ISSUE TITLE
Add a tag for 1.9.3

### ISSUE THREAD

**Issue by jo-so** [sky-map-team/stardroid#219]
Please, add a git tag for the release of version 1.9.3. Otherwise Fdroid's build chain wouldn't start.

**Comment by jaydeetay** [comment]
Looks like I might have been a bit careless with that release and not tagged the cut that I built from. That was bad.  I'll do better for the 1.9.4 release.  Can you tell me how it affects Fdroid?

**Comment by barbeau** [comment]
I believe FDroid just doesn't know about the 1.9.3 release because it's own release process is triggered by Github hooks. In other words, it listens for the tag to be pushed to Github, and then proceeds to pull down that Git tag, build, sign, and release to its own app store.

**Comment by jaydeetay** [comment]
Got it.  Thanks Sean - that makes sense.  I think rather than me trying to
guess at what the code looked like when I cut that release I'll just wait
for the next one and do it properly then.  I'm not sure the Fdroid release
is working at the moment anyway. I have a feeling it got broken and I
disabled it alas.

**Comment by jugendhacker** [comment]
Eventually you could also just tag the specific commit for the release now? Because F-Droid still can't build it because of the missing tag....

**Comment by jondo** [comment]
Yes, please just tag commit 4242d88281973c7ae3e380702d3f121cdb77f288 (with the version number change). You can use the tag `1.9.3-published-fdroid`, then it doesn't matter whether this is exactly the same code as in Google Play.

**Comment by jspricke** [comment]
There is a 1.9.4 tag now, F-Droid picked it up and I've just pushed some fixes to make it build. The new version should be available soon.

**Comment by jaydeetay** [comment]
Thanks Jochen. I'm almost completely ignorant of what's needed for F-droid
so appreciate the help you've given here.
Having a bit of trouble with my set up this morning, but I'll merge your PR
soon.

**Comment by jaydeetay** [comment]
I think with 1.9.4 this bug should be obsolete now....
