### ISSUE TITLE
Use of obsolete 'compile' configuration in Gradle configuration

### ISSUE THREAD

**Issue by UdeshUK** [sky-map-team/stardroid#221]
Gradle configurations use obsolete "compile" configuration which will be removed in end of 2018. Migrate to 'implementation' configuration for dependencies instead of deprecated 'compile'.
[Gradle 3.0 Dependeny Configurations](http://d.android.com/r/tools/update-dependency-configurations.html)

**Comment by jddeep** [comment]
I would like to work on this issue please.

**Comment by jddeep** [comment]
@UdeshUK
