### ISSUE TITLE
build_skymap.sh failing while upgrading dependencies

### ISSUE THREAD

**Issue by utkarsh530** [sky-map-team/stardroid#250]
**Summary:** 

``./build_skymap.sh`` fails with error related to proguard while upgrading dependencies.

**Steps to reproduce:** 
Upgrade dependencies in ``build.gradle (app)`` and ``build.gradle (project)`` and run ``./build_skymap.sh``

**Expected behavior:** 

``./build_skymap.sh`` successful build

**Observed Behaviour**

This error log: 

``
> Task :app:mergeExtDexGmsDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:gmsDebugRuntimeClasspath'.
> Failed to transform file 'guava-24.1-jre.jar' to match attributes {artifactType=android-dex, dexing-is-debuggable=true, dexing-min-sdk=15} using transform DexingTransform
   > Error while dexing.

``

**Comment by jaydeetay** [comment]
Think this is working fine now.
