### ISSUE TITLE
Suggestion: gradle.xml be moved to .gitignore

### ISSUE THREAD

**Issue by utkarsh530** [sky-map-team/stardroid#251]
**Summary:** 

gradle.xml should be moved to .gitignore because I think it must not be tracked by git as it gets changed when we build the project.

**Comment by jaydeetay** [comment]
SGTM.

**Comment by jaydeetay** [comment]
(Sorry - sounds good to me - I meant to say). You are welcome to make a PR for precisely this change if you wish. Otherwise I will.

**Comment by tavishjain** [comment]
@jaydeetay should I proceed with the PR ?

**Comment by jaydeetay** [comment]
I was going to leave it to @utkarsh530 since he filed the bug. Let's give him a chance to respond.

**Comment by tavishjain** [comment]
Sure

**Comment by utkarsh530** [comment]
@jaydeetay okay I'm fixing it.
