### ISSUE TITLE
No proper indication of icons

### ISSUE THREAD

**Issue by tavishjain** [sky-map-team/stardroid#258]
A simple tap on the screen yields some more options that the user can perform
But it is difficult for any random person to recognize and try to understand what those buttons may mean. 
This must be rectified as it may lead to a bad User Experience

**Comment by jaydeetay** [comment]
Well, 'must' is a strong word - I'd say that is a matter of opinion.
However...the UI is in general dated. I think that enabling/disabling layers probably doesn't deserve to be 'front and center' as it is. So I'll definitely reconsider the UX for this in any new UI. But I don't think I'm going to make this change to the current UI.

**Comment by jaydeetay** [comment]
Duplicate of https://github.com/sky-map-team/stardroid/issues/234
