### ISSUE TITLE
Error in Eula Dialog string formatting

### ISSUE THREAD

**Issue by jddeep** [sky-map-team/stardroid#299]
**Summary:** 
Error in Eula Dialog string formatting

**Device and Android version:** 
8.0.0

**Screenshots:** 
![Screenshot (190)](https://user-images.githubusercontent.com/43133646/55927101-71912000-5c31-11e9-9cc4-ccc6ad868935.png)

**Comment by jaydeetay** [comment]
Not sure this is an error - it's supposed to be interpolating the string.
