### ISSUE TITLE
Migrating to androidx issue.

### ISSUE THREAD

**Issue by MuhammadAjmal661** [sky-map-team/stardroid#310]
when ever i migrate the porject to androidx or i upgrade it's  support libraries to 28.0.0 it gives "Process: com.google.android.stardroid, PID: 19086
    android.content.res.Resources$NotFoundException: String resource ID #0x7f0d01d5" exception.

code upgrading issue, when ever i migrate to androidx it gives ResourceNotFound exception

**Comment by penn5** [comment]
Probably has to do with the "star maps" strings system. I haven't read the relevant source but judging by the README its likely to do with this.

**Comment by numanbutt777** [comment]
@MuhammadAjmal661  Can you solve this issue ????

**Comment by jaydeetay** [comment]
Yeah this is tricky. The current build system requires an older version of the gradle plugin...so we're a bit stuck until we can get rid of the old string handling.
