### ISSUE TITLE
Auto mode possible with broken gyroscope? 

### ISSUE THREAD

**Issue by ildar** [sky-map-team/stardroid#326]
I.e. accelerometer and compass work fine. Diagnostics show that clearly! 👍🏻
Old device but i hope still may be useful. 😞

**Comment by ildar** [comment]
Excuse my blindness. found that

**Comment by jaydeetay** [comment]
Glad you found the option! We don't do this automatically as you'd be surprised how many phones report that they don't have a particular sensor but actually do.
