### ISSUE TITLE
Neowise 

### ISSUE THREAD

**Issue by bynbag** [sky-map-team/stardroid#331]
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

**Steps to reproduce:** 

How can we reproduce the issue?

**Expected behavior:** 

What did you expect the app to do?

**Observed behavior:** 

What did you see instead?  Describe your issue in detail here.

**Device and Android version:** 

What make and model device (e.g., Samsung Galaxy S7) did you encounter this on?  What Android version (e.g., Android 4.0 Ice Cream Sandwich) are you running?  Is it the stock version from the manufacturer or a custom ROM?  What version of Google Play Services is running on your device?

**Screenshots:** 

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by jaydeetay** [comment]
Hi! I'm pleased to say we do have a release with Neowise in it. You can find it here on GitHub under "releases". Unfortunately it's not available in Google Play yet - the Play Team is taking a super long time to review apps these days (over a week), so I'm still waiting for them to release our update.

**Comment by bynbag** [comment]
Thank you I did find it. And finding it useful. Shame the clouds are in the way! Thanks for responding and sorting the tread out. First time using github so a bit raw

**Comment by jaydeetay** [comment]
Thanks for jumping through the extra hoops. Hopefully our next release on
the Play Store won't get held up as long.
