### ISSUE TITLE
Regression: crash during startup

### ISSUE THREAD

**Issue by xandro0777** [sky-map-team/stardroid#385]
version 1.9.6-RC2 from FDroid crashes during startup without any user interaction, 1.9.4-neowhisehack worked without any problems.

Hope the crashlog help:

'''
D/Stardroid.StardroidApplication(31787): StardroidApplication: onCreate
D/Stardroid.ApplicationModule(31787): Creating application module for com.google.android.stardroid.StardroidApplication@d780969
D/Stardroid.ApplicationModule(31787): Providing shared preferences
I/Stardroid.ApplicationModule(31787): Initializing LayerManager
D/Stardroid.LayerManager(31787): Creating LayerManager
D/Stardroid.AbstractFileBasedLayer(31787): Loading Proto File: stars.binary...
D/Stardroid.Planet(31787): Lunar phase = 139.76659
D/Stardroid.Planet(31787): Tomorrow's phase = 148.45358
W/Stardroid.AbstractLayer(31787): Renderer not set - aborting: PlanetsLayer
W/UnsafeUtil(31787): platform method missing - proto runtime falling back to safer methods: java.lang.NoSuchMethodException: getByte [class java.lang.Object, long]
E/AndroidRuntime(31787): FATAL EXCEPTION: pool-1-thread-1
E/AndroidRuntime(31787): Process: com.google.android.stardroid, PID: 31787
E/AndroidRuntime(31787): java.lang.NoSuchMethodError: No virtual method putFloat(Ljava/lang/Object;JF)V in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-libart.jar)
E/AndroidRuntime(31787):        at com.google.protobuf.UnsafeUtil$JvmMemoryAccessor.putFloat(UnsafeUtil.java:630)
E/AndroidRuntime(31787):        at com.google.protobuf.UnsafeUtil.putFloat(UnsafeUtil.java:151)
E/AndroidRuntime(31787):        at com.google.protobuf.MessageSchema.mergeFromHelper(MessageSchema.java:3915)
E/AndroidRuntime(31787):        at com.google.protobuf.MessageSchema.mergeFrom(MessageSchema.java:3846)
E/AndroidRuntime(31787):        at com.google.protobuf.CodedInputStreamReader.readMessage(CodedInputStreamReader.java:213)
E/AndroidRuntime(31787):        at com.google.protobuf.CodedInputStreamReader.readMessageBySchemaWithCheck(CodedInputStreamReader.java:181)
E/AndroidRuntime(31787):        at com.google.protobuf.MessageSchema.mergeFromHelper(MessageSchema.java:3959)
E/AndroidRuntime(31787):        at com.google.protobuf.MessageSchema.mergeFrom(MessageSchema.java:3846)
E/AndroidRuntime(31787):        at com.google.protobuf.CodedInputStreamReader.readMessage(CodedInputStreamReader.java:213)
E/AndroidRuntime(31787):        at com.google.protobuf.CodedInputStreamReader.readMessageList(CodedInputStreamReader.java:811)
E/AndroidRuntime(31787):        at com.google.protobuf.MessageSchema.readMessageList(MessageSchema.java:5661)
E/AndroidRuntime(31787):        at com.google.protobuf.MessageSchema.mergeFromHelper(MessageSchema.java:4059)
E/AndroidRuntime(31787):        at com.google.protobuf.MessageSchema.mergeFrom(MessageSchema.java:3846)
E/AndroidRuntime(31787):        at com.google.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1528)
E/AndroidRuntime(31787):        at com.google.protobuf.GeneratedMessageLite$DefaultInstanceBasedParser.parsePartialFrom(GeneratedMessageLite.java:1503)
E/AndroidRuntime(31787):        at com.google.protobuf.GeneratedMessageLite$DefaultInstanceBasedParser.parsePartialFrom(GeneratedMessageLite.java:1491)
E/AndroidRuntime(31787):        at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:215)
E/AndroidRuntime(31787):        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:232)
E/AndroidRuntime(31787):        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:237)
E/AndroidRuntime(31787):        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
E/AndroidRuntime(31787):        at com.google.android.stardroid.layers.AbstractFileBasedLayer.readSourceFile(AbstractFileBasedLayer.java:82)
E/AndroidRuntime(31787):        at com.google.android.stardroid.layers.AbstractFileBasedLayer.access$100(AbstractFileBasedLayer.java:47)
E/AndroidRuntime(31787):        at com.google.android.stardroid.layers.AbstractFileBasedLayer$1.run(AbstractFileBasedLayer.java:65)
E/AndroidRuntime(31787):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(31787):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(31787):        at java.lang.Thread.run(Thread.java:818)
W/ActivityManager(  897):   Force finishing activity 1 com.google.android.stardroid/.activities.SplashScreenActivity
V/WindowManager(  897): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  897): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
W/Stardroid.AbstractLayer(31787): Renderer not set - aborting: MeteorShowerLayer
D/Stardroid.AbstractFileBasedLayer(31787): Loading Proto File: messier.binary...
I/Process (31787): Sending signal. PID: 31787 SIG: 9
I/ActivityManager(  897): Process com.google.android.stardroid (pid 31787) has died
V/WindowManager(  897): removeAppToken make exiting: AppWindowToken{5204d33 token=Token{1ceeeca2 ActivityRecord{1705b86d u0 com.google.android.stardroid/.activities.SplashScreenActivity t17496}}}
''

**Comment by jaydeetay** [comment]
Thanks for the report! I seem to remember there was some duff version of the protocol buffer I had trouble with. I'll take a look when I next do a build. I'm not really involved in the Fdroid builds - they're really a side effect of me cutting new releases for the Play Store so I don't always catch issues with them.

**Comment by jaydeetay** [comment]
Hopefully 1.9.6-RC3 has fixed it. I didn't really intend RC2 to be generally available - it was only supposed to be for internal testers.

**Comment by jaydeetay** [comment]
Yeah - looks like I noted in RC2 that it crashes on some devices.  I wonder why Fdroid has RC2 rather than RC3.

I don't think I have any control about which version they have on their site unfortunately.

https://github.com/sky-map-team/stardroid/releases
