### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [sky-map-team/stardroid#397]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by jaydeetay** [comment]
Thanks for the tip!

Hmm...I wonder how I can get a new build on FDroid - the one they have is
old and known to be broken.

**Comment by barbeau** [comment]
@jaydeetay I think at some point the autoupdate for SkyMap was turned off on F-droid, back when there were issues with the F-droid build:
https://gitlab.com/fdroid/fdroiddata/-/issues/1763

I think submitting a pull request to change `AutoUpdateMode` here:
https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.google.android.stardroid.yml

to `Version %v` would work. See docs here:
https://f-droid.org/en/docs/Build_Metadata_Reference/#autoupdatemode

**Comment by barbeau** [comment]
After auto-update mode is turned back on, then F-Droid should automatically build new releases each time you tag a release on GitHub.

**Comment by jaydeetay** [comment]
Thanks Sean!

**Comment by landry314** [comment]
Well, 1.9.6 - RC2 is the last version on F-Droid, added on Oct 17, 2020.

When it is tagged at Pre-Release, will F-droid pick that up too? 1.9.6 - RC6 is a Final Release and it didn't pick that up.

**Comment by Aga-C** [comment]
@jaydeetay I've noticed there are still no changes to F-Droid. If you'd like, I can add proper metadata to the repository with screenshots and description. Then the description will be also available for translation.

Should I copy description and screenshots from Google Play, or you'd like some other?

**Comment by jaydeetay** [comment]
Feel free! I haven't looked at F-Droid for about a year and even then I
didn't know much about it so your help is appreciated.

**Comment by mondlicht-und-sterne** [comment]
It's showing some now, thanks. Then I'll close here now.
