### ISSUE TITLE
Prereleases not uploaded to Google Store beta channel

### ISSUE THREAD

**Issue by VasilisKos** [sky-map-team/stardroid#405]
That's the purpose of beta channels, isn't it? 😕

**Comment by jaydeetay** [comment]
Hi Vasilis. Why do you think they're not?

**Comment by VasilisKos** [comment]
The Google Store beta version is 1.9.6-RC6, not 1.9.7 - RC1.

**Comment by jaydeetay** [comment]
Ah - yes - that *is* the latest published version.  Do you see a later
version in production?  I haven't pushed out a new version for a few months
on any channel.  Don't be misled by whatever the latest number is in
version control...that version might never reach the beta channel if I find
problems with it during earlier rounds of testing.
