### ISSUE TITLE
Replace the image for Pluto

### ISSUE THREAD

**Issue by jaydeetay** [sky-map-team/stardroid#41]
We have better imagery available now.

**Comment by quentindemetz** [comment]
Looks like this was resolved in https://github.com/sky-map-team/stardroid/commit/ae4c896 - but a release with this image is still needed.

**Comment by jaydeetay** [comment]
Yes, there's a release with it in the beta channel I think (and if not, there soon will be).  I'm aiming for a release roughly once per month (not a strict timetable, just an approximate cadence).

**Comment by jaydeetay** [comment]
Done in 1.8.4
