### ISSUE TITLE
Comet Leonard

### ISSUE THREAD

**Issue by TheReverendCard** [sky-map-team/stardroid#435]
Any chance that comet Leonard will be added for a few weeks?

**Comment by jaydeetay** [comment]
Hi!
Thanks for bringing that to my attention.  I'll see what I can do. Last
time we added a comet it was a bit unsophisticated...just a few points
showing its location at intervals.  Might have to do the same for now.

John

**Comment by jaydeetay** [comment]
Hi - OK this is perhaps a little late, but I added the comet. And the good news is that it should be easier to add the *next* comet as I'm gradually cleaning up the code.  If you register as a beta tester at https://play.google.com/apps/testing/com.google.android.stardroid

then you should get access to the app in a few hours.  I'm reluctant to roll this out to general users too quickly as it contains a lot of fairly risky changes.
