### ISSUE TITLE
App deleted from Google Play 

### ISSUE THREAD

**Issue by VasilisKos** [sky-map-team/stardroid#511]
The app has been deleted today from Google Play. Are you aware of that or is Google responsible? 
The problem is that the Play version was 1.10.3 RC1, while here only version 1.10.1 RC2 is available. Can you please bring it back to Play or at least make the latest version available in GitHub too.

**Comment by jaydeetay** [comment]
So....they need to verify my identity as a developer.  Only they didn't
bother to tell me first - they just took the app done.  It's possible the
notification went to spam...but given that I use gmail you'd *think* that
Google would whitelist their own emails...but maybe not.
Working to restore it.

**Comment by jaydeetay** [comment]
It should be back now.  What a useless shower they are.

Thanks again for letting me know.
